FROM openjdk:7
COPY ./src /usr/src/building_iterators
WORKDIR /usr/src/building_iterators
RUN javac Checker.java Counter.java Filter.java LongerThan.java MySet.java \
Odd.java Primes.java PrintPrimes.java UseIntSets1.java UseIntSets2.java \
UseStringSets1.java UseStringSets2.java
