FROM openjdk:7
COPY ./src /usr/src/folding_a_collection
WORKDIR /usr/src/folding_a_collection
RUN javac MyJoin.java AddIntegers.java LargerIntegerString.java \
ListAddInteger.java MaxIntegers.java MyFold.java examples/Transformer.java \
examples/Lengther.java examples/MyComparator1.java examples/MyComparator2.java \
examples/StringTransformer.java examples/NameDropper1.java \
examples/NameDropper2.java examples/StringAlphabetic1.java \
examples/Sort1.java examples/StringLength1.java examples/Sort2.java \
examples/StringAlphabetic2.java examples/Sort3.java \
examples/StringLength2.java examples/Sort4.java examples/Sort5.java \
examples/UpperCaser1.java examples/StringTransform1.java \
examples/StringTransform2.java examples/UpperCaser2.java \
examples/StringTransform3.java examples/StringTransform4.java \
examples/StringTransform5.java
